var labels = {
	messages : {
		title : "Messages",
		newMessages : "new Messages",
		inbox : "Your inbox",
		inboxLink : "/inc/web-widgets/index.html",
		internalMessageLink : "/inc/web-widgets/index.html"
	},
	resetPassword : {
		emailLabel: "E-mail address",
		errorMessage: "You have entered invalid data. Please try again.",
		emailNotExists: "The email address you requested is not registered in our database.",
		capthcaLabel: "Text verification",
		redirectUrl: "/web-widgets/index.html",
		successMessage: "Your password has been reset."
	},
	passwordUpdate: {
		title: "New Password",
		password: "Password",
		passwordRepeat: "Please repeat your input",
		headerText: "Please enter a new password",
		passwordHeader : "Choose your password (minimum 6 characters).</br>Please only use the following in your member name and password: a-z, A-Z, 0-9, .-!@?*#$.",
		successfullRedirectUrl: "/web-widgets/index.html",
		errorMessage: "You have entered invalid data. Please try again.",
		keyExpired: "You can reset password only once using this link.",
		keyExists: "You cannot enter previously entered password, Please try again.",

	},
	messagesList : {
		title : "Messages",
		date : "Date",
		subject : "Subject",
		newMessages : "new Messages",
		deleteAll : "Delete All",
		inbox : "Your inbox",
		inboxLink : "/us/en/member_area/inbox.html",
		internalMessageLink : "/us/en/member_area/inbox.html?messageId=",
		deleteConfirmation : "Do you really want to delete this message?",
		noMessages: "No messages"
	},
	quick_message : {
		title : "Quick Message",
		defaultMessage : "Send us a message and we will get back to your shortly",
		successMessage : "Message sent!",
		send : "Send"
	},
	toolbox : {
		title : "Toolbox"
	},
	my_toolbox : {
		title : "My Tools"
	},
	literature : {
		title : "My Literature"
	},
	my_projects : {
		title : "My Projects",
		info : "Here you can find your latest filed projects from the Sealing Solutions Configurator."
	},
	registration_wizard : {
		header: "Registration",
		formOfAddress : "Form of address",
		firstName : "First name",
		lastName : "Last Name",
		company : "Company",
		jobTitle : "Job title",
		country : "Country",
		address : "Address",
		city : "City",
		plz : "Postal code",
		email : "E-mail-address",
		repeteEmail : "Repeat your email address",
		phone : "Tel",
		fax : "Fax",
		state : "State",
		pleaseSelect : "Please select",
		language : "Your preferred language",
		step1 : "User Info",
		step2 : "Org Details",
		step3 : "Confirm Password",
		backButton : "Back",
		continueButton : "Continue",
		completeButton : "Complete registration",
		password : "Password",
		repeatPassword : "Repeat password",
		passwordNote1 : "Choose your password (minimum 6 characters).",
		passwordNote2 : "Please only use the following in your member name and password: a-z, A-Z, 0-9, .-!@?*#$.",
		infoMessage1 : "These fields are required",
		infoMessage2 : "All details given on this page are dealt with confidentially.",
		newsletterText : "I would like to receive the Trelleborg Sealing Solutions Newsletter.",
		aggrement: "I agree to the <a target='_blank' title='Terms of Use' href='/global/en/legalnotice.html'>Terms of Use</a>, and <a target='_blank' title='Privacy Policy' href='/global/en/privacypolicy.html'>Privacy Policy</a><sup>*</sup>",
		error : "Please fill in all mandatory fields",
		errorEmailUsed : "The entered email address is already in use."

	},

	contact_form : {
		headerNote : "Please note: If you are a registered member please login. Your contact details will then automatically be filled into the contact form",
		formOfAddress : "Form of address",
		firstName : "First name",
		lastName : "Last Name",
		company : "Company",
		jobTitle : "Job title",
		country : "Country",
		address : "Address",
		city : "City",
		plz : "Postal code",
		email : "E-mail-address",
		repeteEmail : "Repeat your email address",
		phone : "Tel",
		requestType : "Request type",
		password : "Password",
		repeatPassword : "Repeat password",
		message : "Message",
		captcha : "Captcha",
		state : "State",
		message : "Message",
		requestType : "Request type",
		state : "State",
		clickHere : "Click here",
		language : "Your preferred language",
		send : "Send",
		consent : "Consent",
		pleaseSelect : "Please select",
		error : "Please fill in all mandatory fields",
		errorEmailUsed : "The entered email address is already in use.",
		newsletter : "I would like to receive the Trelleborg Sealing Solutions Newsletter.",
		clickHereAction1 : "to use this data and create a member registration. As a registered member you can benefit from our useful Services and Tools. Simply add some extra information and you're all set.",
		clickHereAction2 : "to remove registration fields and only send a contact request.",
		infoMessage1 : "These fields are required",
		infoMessage2 : "All details given on this page are dealt with confidentially.",
		requestTypeP : "Products and Solutions",
		requestTypeF : "Website Feedback",
		requestTypeQ : "Other Questions",
		successSent : "Your request has been sent successfully.",
		aggrement: "I agree to the <a target='_blank' title='Terms of Use' href='/global/en/legalnotice.html'>Terms of Use</a>, and <a target='_blank' title='Privacy Policy' href='/global/en/privacypolicy.html'>Privacy Policy</a><sup>*</sup>"
	},
	user_profile_form: {
		title : "My profile",
		firstName : "First name",
		lastName : "Last name",
		email : "E-mail address",
		responsibleMC : "Your responsible TSS Marketing Company",
		changeCountryInfo : "If you would like to change your country please delete this account and register again",
		newsletterText : "I would like to receive the Trelleborg Sealing Solutions Newsletter.",
		subscribe : "Subscribe",
		memberMessageNotification : "I want to be notified via Email about Member Area Updates",
		skillsSectionTitle : "Skills, Experience, Interests",
		contactDetailsTitle : "Contact details",
		requiredFields : "These fields are required",
		yourCountry : "Your Country",
		memberMessageNoification : "Member message notification",
		saveData : "Save data",
		saveDataText : "I want to save my updated data information",
		deleteAccount : "Delete account",
		deleteAccountText : "I want to delete this account",
		company : "Company",
		jobTitle : "Job title",
		address : "Address",
		describeYourself : "describe yourself",
		password : "Password",
		newPassword : "New Password",
		confirmPassword : "Repeat Password",
		passwordNote : "Please only use the following in your member name and password: a-z, A-Z, 0-9, .-!@?*#$.",
		passwordNote2 : "Choose your password (minimum 6 characters).",
		city : "City",
		postalCode :  "Postal code",
		phone : "Tel",
		fax : "Fax",
		error : "Please fill in all mandatory fields",
		successMessage : "User have been updated successfully.",
		changePassword : "Change Password?",
		confirmDelete : "All data will be unrecoverable deleted",
		errorEmailUsed : "The entered email address is already in use."
	},
	login_form : {
		memberAreaLink : "/us/en/member_area/member_area.html",
		registerLink : "/global/en/registration/register.html",
		forgotPassword : "Forgotten Password",
		register : "Register here",
		memberArea : "Member Area",
		logout : "Logout",
		emailField : "E-mail address",
		passwordField : "Password",
		loggedIn: "You are logged in,",
		logoutMessage: "You have logged out.",
		loginFaildMessage: "Authentication failed."
	},
	sscTerms: {
		linkLabel : "Go to Sealing Solutions Configurator",
		checkboxLabel : "I have read the above terms and agree"
	},
	languages: {
		languageAT : "German - AT",
		languageBE : "English - BE",
		languageBG : "Bulgarian",
		languageBR : "Portuguese",
		languageCH : "German - CH",
		languageCN : "Chinese",
		languageCZ : "Czech",
		languageDE : "German - DE",
		languageDK : "Danish",
		languageES : "Spanish",
		languageFI : "Finnish",
		languageFR : "French",
		languageGB : "English - GB",
		languageUK : "English - UK",
		languageHR : "Croatian",
		languageHU : "Hungarian",
		languageIN : "English - IN",
		languageIN : "Hindi",
		languageIT : "Italian",
		languageJP : "Japanese",
		languageKR : "Korean",
		languageNL : "Dutch",
		languageNO : "Norwegian",
		languagePL : "Polish",
		languageRU : "Russian",
		languageSE : "Swedish",
		languageTR : "Turkish",
		languageTW : "Taiwanese",
		languageUS : "English - USA"
	}
}
